<?php
defined( 'ABSPATH' ) || exit;

final class RSV_Admin {
	public function register() {
		add_action( 'admin_menu', array( $this, 'menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'assets' ) );
		add_action( 'admin_post_rsv_moderate_report', array( $this, 'moderate_report' ) );
		add_action( 'admin_post_rsv_repair', array( $this, 'repair' ) );
		add_action( 'admin_post_rsv_migrate', array( $this, 'migrate' ) );
	}
	public function menu() {
		if ( ! RSV_Security::can( RSV_Contracts::CAP_MANAGE ) && ! current_user_can( 'manage_options' ) ) return;
		add_menu_page( __( 'Reels', RSV_TEXT_DOMAIN ), __( 'Reels', RSV_TEXT_DOMAIN ), RSV_Contracts::CAP_MANAGE, 'rsv-reels', array( $this, 'dashboard' ), 'dashicons-video-alt3', 28 );
		add_submenu_page( 'rsv-reels', __( 'Moderation', RSV_TEXT_DOMAIN ), __( 'Moderation', RSV_TEXT_DOMAIN ), RSV_Contracts::CAP_MODERATE, 'rsv-moderation', array( $this, 'moderation' ) );
		add_submenu_page( 'rsv-reels', __( 'Diagnostics', RSV_TEXT_DOMAIN ), __( 'Diagnostics', RSV_TEXT_DOMAIN ), RSV_Contracts::CAP_MANAGE, 'rsv-diagnostics', array( $this, 'diagnostics' ) );
	}
	public function assets( $hook ) { if ( false !== strpos( $hook, 'rsv-' ) ) wp_enqueue_style( 'rsv-admin', RSV_URL . 'assets/css/admin.css', array(), RSV_VERSION ); }
	public function dashboard() {
		$s=RSV_Diagnostics::summary(); ?><div class="wrap rsv-admin"><h1><?php esc_html_e('Reels Operations',RSV_TEXT_DOMAIN); ?></h1><div class="rsv-admin-grid"><div><strong><?php echo absint($s['published_reels']); ?></strong><span><?php esc_html_e('Published Reels',RSV_TEXT_DOMAIN); ?></span></div><div><strong><?php echo absint($s['open_reports']); ?></strong><span><?php esc_html_e('Open reports',RSV_TEXT_DOMAIN); ?></span></div><div><strong><?php echo esc_html($s['file10_ready']?__('Ready',RSV_TEXT_DOMAIN):__('Unavailable',RSV_TEXT_DOMAIN)); ?></strong><span><?php esc_html_e('File 10',RSV_TEXT_DOMAIN); ?></span></div><div><strong><?php echo esc_html($s['safe_mode']?__('Safe Mode',RSV_TEXT_DOMAIN):__('Healthy',RSV_TEXT_DOMAIN)); ?></strong><span><?php esc_html_e('Runtime state',RSV_TEXT_DOMAIN); ?></span></div></div></div><?php
	}
	public function moderation() {
		global $wpdb;
		$reports=RSV_Helpers::table('reports');
		$rows=$wpdb->get_results("SELECT * FROM $reports WHERE status IN ('submitted','triaged','appealed') ORDER BY CASE reason_code WHEN 'child-safety' THEN 0 WHEN 'harm' THEN 0 WHEN 'false-claim' THEN 1 WHEN 'medical-claim' THEN 1 WHEN 'privacy' THEN 1 WHEN 'patient-privacy' THEN 1 WHEN 'impersonation' THEN 1 WHEN 'scam' THEN 1 WHEN 'abuse' THEN 2 WHEN 'harassment' THEN 2 WHEN 'copyright' THEN 2 WHEN 'spam' THEN 2 ELSE 3 END ASC, updated_at ASC LIMIT 100",ARRAY_A); ?>
		<div class="wrap rsv-admin"><h1><?php esc_html_e('Reel Moderation',RSV_TEXT_DOMAIN); ?></h1><?php if(!$rows): ?><p><?php esc_html_e('No open reports.',RSV_TEXT_DOMAIN); ?></p><?php else: ?><table class="widefat striped"><thead><tr><th>ID</th><th><?php esc_html_e('Reel',RSV_TEXT_DOMAIN); ?></th><th><?php esc_html_e('Reason / details',RSV_TEXT_DOMAIN); ?></th><th><?php esc_html_e('Risk / route',RSV_TEXT_DOMAIN); ?></th><th><?php esc_html_e('Status',RSV_TEXT_DOMAIN); ?></th><th><?php esc_html_e('Decision',RSV_TEXT_DOMAIN); ?></th></tr></thead><tbody><?php foreach($rows as $row): $normalized=RSV_Contracts::normalize_report_reason($row['reason_code'])?:sanitize_key($row['reason_code']);$risk=RSV_Current_Plan::report_risk_profile($normalized); ?><tr><td><?php echo absint($row['id']); ?></td><td><?php echo absint($row['reel_id']); ?></td><td><strong><?php echo esc_html(RSV_Helpers::label($normalized)); ?></strong><br><?php echo esc_html($row['details']); ?><?php if($row['appeal_text']): ?><hr><strong><?php esc_html_e('Appeal:',RSV_TEXT_DOMAIN); ?></strong> <?php echo esc_html($row['appeal_text']); ?><?php endif; ?></td><td><strong><?php echo esc_html(RSV_Helpers::label($risk['tier']??'high')); ?></strong><br><?php echo esc_html($risk['expert']??'moderation'); ?><br><?php echo esc_html($risk['sla']??'priority'); ?></td><td><?php echo esc_html($row['status']); ?></td><td><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('rsv_moderate_'.$row['id']); ?><input type="hidden" name="action" value="rsv_moderate_report"><input type="hidden" name="report_id" value="<?php echo absint($row['id']); ?>"><input type="hidden" name="version" value="<?php echo absint($row['version']); ?>"><select name="decision" required><option value=""><?php esc_html_e('Choose',RSV_TEXT_DOMAIN); ?></option><?php foreach(RSV_Contracts::MODERATION_DECISIONS as $decision): ?><option value="<?php echo esc_attr($decision); ?>"><?php echo esc_html(RSV_Helpers::label($decision)); ?></option><?php endforeach; ?></select><textarea name="reason" minlength="10" required placeholder="<?php esc_attr_e('Decision reason',RSV_TEXT_DOMAIN); ?>"></textarea><button class="button button-primary" type="submit"><?php esc_html_e('Apply',RSV_TEXT_DOMAIN); ?></button></form></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div><?php
	}
	public function diagnostics() {
		$s=RSV_Diagnostics::summary(); ?><div class="wrap rsv-admin"><h1><?php esc_html_e('Reels Diagnostics',RSV_TEXT_DOMAIN); ?></h1><pre><?php echo esc_html(wp_json_encode($s,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)); ?></pre><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('rsv_repair'); ?><input type="hidden" name="action" value="rsv_repair"><button class="button button-primary" type="submit"><?php esc_html_e('Run safe repair',RSV_TEXT_DOMAIN); ?></button></form><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('rsv_migrate'); ?><input type="hidden" name="action" value="rsv_migrate"><label><input type="checkbox" name="dry_run" value="1" checked> <?php esc_html_e('Dry run',RSV_TEXT_DOMAIN); ?></label><button class="button" type="submit"><?php esc_html_e('Run legacy migration batch',RSV_TEXT_DOMAIN); ?></button></form></div><?php
	}
	public function moderate_report(){if(!RSV_Security::can(RSV_Contracts::CAP_MODERATE))wp_die( esc_html__( 'Forbidden', RSV_TEXT_DOMAIN ), '', array( 'response' => 403 ) );$id=absint($_POST['report_id']??0);check_admin_referer('rsv_moderate_'.$id);$result=RSV_Reels::moderate($id,$_POST['decision']??'',$_POST['reason']??'',absint($_POST['version']??0));$url=add_query_arg('rsv_result',is_wp_error($result)?$result->get_error_code():'success',admin_url('admin.php?page=rsv-moderation'));wp_safe_redirect($url);exit;}
	public function repair(){if(!RSV_Security::can(RSV_Contracts::CAP_MANAGE)&&!current_user_can('manage_options'))wp_die( esc_html__( 'Forbidden', RSV_TEXT_DOMAIN ), '', array( 'response' => 403 ) );check_admin_referer('rsv_repair');RSV_Diagnostics::repair();wp_safe_redirect(add_query_arg('rsv_repair','complete',admin_url('admin.php?page=rsv-diagnostics')));exit;}
	public function migrate(){if(!RSV_Security::can(RSV_Contracts::CAP_MANAGE)&&!current_user_can('manage_options'))wp_die( esc_html__( 'Forbidden', RSV_TEXT_DOMAIN ), '', array( 'response' => 403 ) );check_admin_referer('rsv_migrate');$result=RSV_Migration::migrate_legacy(!empty($_POST['dry_run']),100);set_transient('rsv_last_migration_result',$result,300);wp_safe_redirect(admin_url('admin.php?page=rsv-diagnostics'));exit;}
}
