<?php
defined( 'ABSPATH' ) || exit;

trait RSV_Future30_Feature_Write_Trait {
	public function series_list() { $rows=self::object_rows('F11-FUT-001',0,0,50);foreach($rows as &$row)unset($row['owner_id']);return rest_ensure_response($rows); }
	public function series_create( $request ) { $p=(array)$request->get_json_params();$rate=RSV_Security::rate_limit('future30_series',30,HOUR_IN_SECONDS);if(is_wp_error($rate))return $rate;$idem=$request->get_header('Idempotency-Key');$begin=RSV_Security::idempotency_begin('future30_series',$idem,$p);if(is_wp_error($begin))return $begin;if(!empty($begin['replay']))return rest_ensure_response($begin['response']);$refs=array_values(array_unique(array_map('sanitize_text_field',(array)($p['ordered_reels']??array()))));if(count($refs)>100){RSV_Security::idempotency_fail('future30_series',$idem);return RSV_Helpers::error('rsv_series_too_large',__('A Reel series may contain at most 100 Reels.',RSV_TEXT_DOMAIN),422);}foreach($refs as $ref)if(!self::canonical_ref_public_valid('File 11',$ref,'series')){RSV_Security::idempotency_fail('future30_series',$idem);return RSV_Helpers::error('rsv_series_reel_invalid',__('Every series item must be a current public Reel.',RSV_TEXT_DOMAIN),422);}return self::idempotent_finish_result('future30_series',$idem,self::put_object('F11-FUT-001','series',0,$p['title']??'',array('description'=>$p['description']??'','difficulty'=>$p['difficulty']??'','ordered_reels'=>$refs),$p['public_id']??'')); }
	public function path_list() { $rows=self::object_rows('F11-FUT-002',0,0,50);foreach($rows as &$row)unset($row['owner_id']);return rest_ensure_response($rows); }
	public function path_create( $request ) { $p=(array)$request->get_json_params();$rate=RSV_Security::rate_limit('future30_learning_paths',30,HOUR_IN_SECONDS);if(is_wp_error($rate))return $rate;$idem=$request->get_header('Idempotency-Key');$begin=RSV_Security::idempotency_begin('future30_learning_path',$idem,$p);if(is_wp_error($begin))return $begin;if(!empty($begin['replay']))return rest_ensure_response($begin['response']);$refs=array_values(array_unique(array_map('sanitize_text_field',(array)($p['file05_course_refs']??array()))));foreach($refs as $ref)if(true!==apply_filters('rsv_future30_file05_public_ref_valid',false,$ref)){RSV_Security::idempotency_fail('future30_learning_path',$idem);return RSV_Helpers::error('rsv_learning_ref_invalid',__('Every learning reference must be current and public according to File 05.',RSV_TEXT_DOMAIN),422);}$steps=array_slice((array)($p['steps']??array()),0,100);return self::idempotent_finish_result('future30_learning_path',$idem,self::put_object('F11-FUT-002','learning_path',0,$p['title']??'',array('level'=>RSV_Helpers::enum($p['level']??'beginner',array('beginner','intermediate','advanced'),'beginner'),'description'=>$p['description']??'','steps'=>$steps,'file05_course_refs'=>$refs),$p['public_id']??'')); }

	public function reel_feature_get( $request ) {
		list($fid,$def)=self::feature($request['feature']); if(!$fid)return RSV_Helpers::error('rsv_future_unknown',__('Unknown future feature.',RSV_TEXT_DOMAIN),404);if(!self::generic_public_allowed($fid))return RSV_Helpers::error('rsv_future_private',__('This capability is private and available only through its dedicated endpoint.',RSV_TEXT_DOMAIN),404);$reel=self::reel($request['id']);if(is_wp_error($reel))return $reel;
		$public=RSV_Security::can_view_reel($reel); if(!$public)return RSV_Helpers::error('rsv_not_found',__('Reel not found.',RSV_TEXT_DOMAIN),404);
		$projection=self::public_projection($fid,$reel);return rest_ensure_response(array('feature_id'=>$fid,'definition'=>$def,'objects'=>$projection['objects'],'edges'=>$projection['edges']));
	}

	public function reel_feature_write( $request ) {
		list( $fid, $def ) = self::feature( $request['feature'] );
		if ( ! $fid ) return RSV_Helpers::error( 'rsv_future_unknown', __( 'Unknown future feature.', RSV_TEXT_DOMAIN ), 404 );
		if ( ! self::generic_write_allowed( $fid ) ) return RSV_Helpers::error( 'rsv_future_dedicated_endpoint', __( 'Use the dedicated protected endpoint for this capability.', RSV_TEXT_DOMAIN ), 400 );
		$reel = self::reel( $request['id'], true );
		if ( is_wp_error( $reel ) ) return $reel;
		$rate = RSV_Security::rate_limit( 'future30_mutation', 120, HOUR_IN_SECONDS );
		if ( is_wp_error( $rate ) ) return $rate;
		$p     = (array) $request->get_json_params();
		$idem  = $request->get_header( 'Idempotency-Key' );
		$scope = 'future30_' . strtolower( str_replace( '-', '_', $fid ) );
		$begin = RSV_Security::idempotency_begin( $scope, $idem, $p );
		if ( is_wp_error( $begin ) ) return $begin;
		if ( ! empty( $begin['replay'] ) ) return rest_ensure_response( $begin['response'] );

		$response = RSV_DB::transaction(
			static function () use ( $fid, $def, $reel, $p, $scope, $idem ) {
				$result = self::feature_write( $fid, $reel, $p );
				if ( is_wp_error( $result ) ) return $result;
				$payload = array( 'ok' => true, 'feature_id' => $fid, 'result' => $result );
				if ( ! RSV_Security::idempotency_finish( $scope, $idem, $payload )
					|| ! RSV_Helpers::audit( 'reel', $reel['id'], 'future30_write', '', '', $fid, array( 'feature' => $def['slug'] ) )
					|| ! RSV_Helpers::outbox( 'ReelFutureCapabilityUpdated', 'reel', $reel['id'], array( 'reel_public_id' => $reel['public_id'], 'feature_id' => $fid ) ) ) {
					return RSV_Helpers::error( 'rsv_future30_evidence_failed', __( 'The Future30 change could not be committed with complete replay, audit and event evidence.', RSV_TEXT_DOMAIN ), 500 );
				}
				return $payload;
			}
		);
		if ( is_wp_error( $response ) ) {
			RSV_Security::idempotency_fail( $scope, $idem );
			return $response;
		}
		return rest_ensure_response( $response );
	}

	private static function feature_write( $fid, $reel, $p ) {
		switch($fid){
			case 'F11-FUT-003': $owner=RSV_Helpers::text($p['target_owner']??'',30);$ref=RSV_Helpers::text($p['target_ref']??'',255);if(!self::canonical_ref_public_valid($owner,$ref,'related-knowledge'))return RSV_Helpers::error('rsv_related_ref_invalid',__('The related knowledge reference is not currently public and valid.',RSV_TEXT_DOMAIN),422);return self::put_edge($fid,$reel['id'],'related-knowledge',$owner,$ref,$p,0,0);
			case 'F11-FUT-004': $time=self::validate_time_range($reel,$p['start_second']??0,$p['end_second']??0);if(is_wp_error($time))return $time;$owner=RSV_Helpers::text($p['source_owner']??'',30);$ref=RSV_Helpers::text($p['source_ref']??'',255);if(!self::canonical_ref_public_valid($owner,$ref,'citation'))return RSV_Helpers::error('rsv_citation_ref_invalid',__('The cited source reference is not currently public and valid.',RSV_TEXT_DOMAIN),422);return self::put_edge($fid,$reel['id'],'timestamp-citation',$owner,$ref,$p,$time['start'],$time['end']);
			case 'F11-FUT-005': $owner=RSV_Helpers::text($p['source_owner']??'File 06',30);$refs=array_values(array_unique(array_map('sanitize_text_field',(array)($p['source_refs']??array()))));if(!$refs)return RSV_Helpers::error('rsv_evidence_source_required',__('At least one current public evidence reference is required.',RSV_TEXT_DOMAIN),422);foreach($refs as $ref)if(!self::canonical_ref_public_valid($owner,$ref,'evidence'))return RSV_Helpers::error('rsv_evidence_ref_invalid',__('An evidence reference is not currently public and valid.',RSV_TEXT_DOMAIN),422);return self::put_object($fid,'evidence_layer',$reel['id'],$p['title']??'Evidence',array('grade'=>$p['grade']??'','source_owner'=>$owner,'source_refs'=>$refs,'claim_scope'=>$p['claim_scope']??'','limitations'=>$p['limitations']??''),$p['public_id']??'');
			case 'F11-FUT-006': $ref=RSV_Helpers::text($p['replacement_reel_ref']??'',255);if(!self::canonical_ref_public_valid('File 11',$ref,'supersession'))return RSV_Helpers::error('rsv_replacement_reel_invalid',__('The replacement Reel is not currently public and valid.',RSV_TEXT_DOMAIN),422);return self::put_edge($fid,$reel['id'],'supersedes','File 11',$ref,array('reason'=>$p['reason']??'','effective_at'=>$p['effective_at']??RSV_Helpers::now()));
			case 'F11-FUT-007': return self::put_object($fid,'version_snapshot',$reel['id'],$p['label']??('v'.$reel['version']),array('reel_version'=>$reel['version'],'title'=>$reel['title'],'caption'=>$reel['caption'],'topic'=>$reel['topic'],'language'=>$reel['language'],'snapshot_hash'=>hash('sha256',RSV_Helpers::json_encode(array($reel['title'],$reel['caption'],$reel['topic'],$reel['language'],$reel['version'])))),$p['public_id']??'');
			case 'F11-FUT-008': $mode=RSV_Helpers::enum($p['mode']??'',array('side-by-side','cut','green-screen','quote-clip','response','teaching-overlay'),'response');$source_ref=RSV_Helpers::text($p['source_reel_ref']??'',255);if(!self::canonical_ref_public_valid('File 11',$source_ref,'remix-source'))return RSV_Helpers::error('rsv_remix_source_invalid',__('The source Reel is not currently public and valid.',RSV_TEXT_DOMAIN),422);$source=RSV_Repository::find($source_ref,true);if(!$source||true!==apply_filters('rsv_future30_remix_allowed',false,$source,$reel,$mode,get_current_user_id()))return RSV_Helpers::error('rsv_remix_not_allowed',__('Current remix permission, rights and patient-consent policy do not allow this reuse.',RSV_TEXT_DOMAIN),403);$derivative=RSV_Helpers::text($p['file10_derivative_ref']??'',255);if(!$derivative||true!==apply_filters('rsv_future30_file10_derivative_valid',false,$derivative,$reel,$mode))return RSV_Helpers::error('rsv_remix_derivative_invalid',__('A current File 10 media derivative is required for this remix.',RSV_TEXT_DOMAIN),422);return self::put_edge($fid,$reel['id'],$mode,'File 11',$source_ref,array('file10_derivative_ref'=>$derivative,'attribution_required'=>true,'patient_media_default_denied'=>true,'permission_rechecked'=>true));
			case 'F11-FUT-009': return self::put_object($fid,'remix_policy',$reel['id'],'Remix policy',array('audio_reuse'=>!empty($p['audio_reuse']),'video_cut'=>!empty($p['video_cut']),'response'=>!empty($p['response']),'green_screen'=>!empty($p['green_screen']),'educational_quote'=>!empty($p['educational_quote']),'download'=>!empty($p['download']),'patient_case_default'=>'deny'),$p['public_id']??'');
			case 'F11-FUT-010': return self::put_object($fid,'template',$reel['id'],$p['title']??'Reel Template',array('template_type'=>$p['template_type']??'clinical-pearl','sections'=>(array)($p['sections']??array()),'max_seconds'=>min(600,max(60,absint($p['max_seconds']??180))),'file10_media_recipe_ref'=>$p['file10_media_recipe_ref']??''),$p['public_id']??'');
			case 'F11-FUT-011': $owner=RSV_Helpers::text($p['question_owner']??'File 21',30);$ref=RSV_Helpers::text($p['question_ref']??'',255);if(!self::canonical_ref_public_valid($owner,$ref,'question'))return RSV_Helpers::error('rsv_question_ref_invalid',__('The question reference is not currently public and valid.',RSV_TEXT_DOMAIN),422);return self::put_edge($fid,$reel['id'],'answers-question',$owner,$ref,array('question_excerpt'=>$p['question_excerpt']??''));
			case 'F11-FUT-012': $ref=RSV_Helpers::text($p['user_ref']??'',255);if(!self::identity_ref_valid($ref,'coauthor'))return RSV_Helpers::error('rsv_coauthor_identity_invalid',__('The co-author identity reference is not currently verified.',RSV_TEXT_DOMAIN),422);$accepted=!empty($p['accepted']);if($accepted&&true!==apply_filters('rsv_future30_coauthor_consent_valid',false,$ref,$reel,get_current_user_id()))return RSV_Helpers::error('rsv_coauthor_consent_invalid',__('The co-author has not provided a current verifiable acceptance for this Reel.',RSV_TEXT_DOMAIN),422);return self::put_edge($fid,$reel['id'],'coauthor','File 00',$ref,array('role'=>$p['role']??'co-author','accepted'=>$accepted));
			case 'F11-FUT-013': $ref=RSV_Helpers::text($p['reviewer_ref']??'',255);if(!self::identity_ref_valid($ref,'peer-reviewer'))return RSV_Helpers::error('rsv_reviewer_identity_invalid',__('The reviewer identity reference is not currently verified.',RSV_TEXT_DOMAIN),422);$decision=RSV_Helpers::enum($p['decision']??'',array('approved','changes-requested','rejected'),'changes-requested');$attestation=RSV_Helpers::text($p['attestation_ref']??'',255);if(!$attestation||true!==apply_filters('rsv_future30_peer_review_attestation_valid',false,$attestation,$ref,$reel,$decision))return RSV_Helpers::error('rsv_peer_review_attestation_invalid',__('A current reviewer-signed or provider-verified review attestation is required.',RSV_TEXT_DOMAIN),422);return self::put_edge($fid,$reel['id'],'peer-review','File 00',$ref,array('decision'=>$decision,'attestation_ref'=>$attestation,'reviewed_at'=>$p['reviewed_at']??RSV_Helpers::now(),'notes'=>$p['notes']??'','conflict_declared'=>!empty($p['conflict_declared'])));
			case 'F11-FUT-014': $lang=RSV_Helpers::text($p['language']??'',20);if(!$lang)return RSV_Helpers::error('rsv_language_required',__('Language is required.',RSV_TEXT_DOMAIN),422);if(!empty($p['is_source']))return RSV_Helpers::error('rsv_language_source_canonical',__('The original source language is the canonical Reel language; only additional linked languages may be added here.',RSV_TEXT_DOMAIN),422);if(strtolower($lang)===strtolower((string)$reel['language']))return RSV_Helpers::error('rsv_language_duplicate_source',__('The original source language must not be duplicated as a linked translation.',RSV_TEXT_DOMAIN),409);$existing=self::edge_rows($fid,$reel['id'],20);$translation_count=0;foreach($existing as $edge){$edge_lang=RSV_Helpers::text($edge['payload']['language']??'',20);if($edge_lang&&strtolower($edge_lang)===strtolower($lang))return RSV_Helpers::error('rsv_language_duplicate',__('This language version is already linked.',RSV_TEXT_DOMAIN),409);$translation_count++;}if($translation_count>=9)return RSV_Helpers::error('rsv_language_limit',__('A Reel may have the original source language plus at most nine linked language versions.',RSV_TEXT_DOMAIN),422);$linked=RSV_Helpers::text($p['linked_reel_ref']??'',255);if($linked&&!self::canonical_ref_public_valid('File 11',$linked,'translated-reel'))return RSV_Helpers::error('rsv_translated_reel_invalid',__('The linked translated Reel is not currently public and valid.',RSV_TEXT_DOMAIN),422);return self::put_edge($fid,$reel['id'],'language-version','translation-provider',$linked?:$lang,array('language'=>$lang,'is_source'=>false,'source_language'=>$reel['language'],'translation_status'=>$p['translation_status']??'candidate','human_reviewed'=>!empty($p['human_reviewed'])));
			case 'F11-FUT-015': $lang=RSV_Helpers::text($p['language']??'',20);if(!$lang)return RSV_Helpers::error('rsv_language_required',__('Language is required.',RSV_TEXT_DOMAIN),422);$dubbing=!empty($p['dubbing']);if($dubbing&&(empty($p['creator_voice_consent'])||true!==apply_filters('rsv_future30_voice_consent_valid',false,$reel,get_current_user_id(),$lang)))return RSV_Helpers::error('rsv_voice_consent_required',__('Explicit current creator voice consent must be verified by the canonical consent provider before AI dubbing.',RSV_TEXT_DOMAIN),422);$request=array('reel_public_id'=>$reel['public_id'],'video_id'=>absint($reel['video_id']),'language'=>$lang,'dubbing'=>$dubbing,'lip_sync'=>($dubbing&&!empty($p['lip_sync'])),'creator_voice_consent'=>($dubbing&&!empty($p['creator_voice_consent'])),'ai_label_required'=>true,'original_audio_option_required'=>true,'human_review_required'=>true,'auto_publish'=>false);$response=apply_filters('rsv_future30_translation_dubbing_request',null,$request);if(!is_array($response))return RSV_Helpers::error('rsv_translation_provider_unavailable',__('Translation/dubbing provider is unavailable. Nothing was published.',RSV_TEXT_DOMAIN),503);$track_ref=RSV_Helpers::text($response['track_ref']??'',255);if($dubbing&&(!$track_ref||true!==apply_filters('rsv_future30_file10_track_ref_valid',false,$track_ref,$reel,$lang)))return RSV_Helpers::error('rsv_translation_track_invalid',__('The generated File 10 track reference is not verified.',RSV_TEXT_DOMAIN),422);return self::put_object($fid,'translation_request',$reel['id'],'AI translation/dubbing',$request+array('track_ref'=>$track_ref,'status'=>RSV_Helpers::text($response['status']??'candidate',30)));
			case 'F11-FUT-016': $request=array('reel_public_id'=>$reel['public_id'],'video_id'=>absint($reel['video_id']),'language'=>$reel['language']);$response=apply_filters('rsv_future30_searchable_transcript',null,$request);if(!is_array($response))return RSV_Helpers::error('rsv_transcript_provider_unavailable',__('The reviewed transcript is unavailable.',RSV_TEXT_DOMAIN),503);$transcript_ref=RSV_Helpers::text($response['transcript_ref']??'',255);if(empty($response['reviewed'])||!$transcript_ref||true!==apply_filters('rsv_future30_transcript_ref_public_valid',false,$transcript_ref,$reel))return RSV_Helpers::error('rsv_transcript_not_reviewed',__('Only a current reviewed public transcript may be linked for discovery.',RSV_TEXT_DOMAIN),422);$projection=array('provider'=>'File 10','transcript_ref'=>$transcript_ref,'language'=>$response['language']??$reel['language'],'reviewed'=>true,'index_owner'=>'File 26');do_action('rsv_transcript_ready_for_index','file11',$reel['public_id'],$projection);return self::put_object($fid,'transcript_projection',$reel['id'],'Searchable transcript',$projection);
			case 'F11-FUT-017': $time=self::validate_time_range($reel,$p['start_second']??0,$p['end_second']??0);if(is_wp_error($time))return $time;return self::put_edge($fid,$reel['id'],'chapter','File 11',$p['slug']??RSV_Helpers::public_id('chapter'),array('title'=>$p['title']??'','summary'=>$p['summary']??''),$time['start'],$time['end']);
			case 'F11-FUT-018': $remedies=array_values(array_unique(array_map('sanitize_text_field',(array)($p['remedy_refs']??array()))));$diseases=array_values(array_unique(array_map('sanitize_text_field',(array)($p['disease_refs']??array()))));$books=array_values(array_unique(array_map('sanitize_text_field',(array)($p['book_refs']??array()))));foreach(array_merge($remedies,$diseases,$books) as $ref)if(!self::canonical_ref_public_valid('File 06',$ref,'knowledge-card'))return RSV_Helpers::error('rsv_knowledge_ref_invalid',__('A knowledge-card reference is not currently public and valid.',RSV_TEXT_DOMAIN),422);return self::put_object($fid,'knowledge_card',$reel['id'],$p['title']??$reel['title'],array('summary'=>$p['summary']??'','key_points'=>array_slice((array)($p['key_points']??array()),0,20),'remedy_refs'=>$remedies,'disease_refs'=>$diseases,'book_refs'=>$books,'difficulty'=>$p['difficulty']??'','source_refs'=>array_slice((array)($p['source_refs']??array()),0,30)),$p['public_id']??'');
			case 'F11-FUT-019': $questions=(array)($p['questions']??array());if(count($questions)<1||count($questions)>5)return RSV_Helpers::error('rsv_quiz_size_invalid',__('A Reel quiz must contain 1 to 5 questions.',RSV_TEXT_DOMAIN),422);return self::put_object($fid,'micro_quiz',$reel['id'],$p['title']??'Quick learning check',array('questions'=>$questions,'streaks'=>false,'ranking_effect'=>false),$p['public_id']??'');
			case 'F11-FUT-024': return self::put_object($fid,'explanation_policy',$reel['id'],'Why this Reel',array('allowed_reasons'=>(array)($p['allowed_reasons']??array('topic-interest','followed-doctor','recent-learning','diversity','latest')),'commercial_reason'=>false,'donor_reason'=>false),$p['public_id']??'');
			case 'F11-FUT-028': return self::run_safety_scan($reel,$p);
			case 'F11-FUT-030': $owner=RSV_Helpers::text($p['target_owner']??'File 06',30);$ref=RSV_Helpers::text($p['target_ref']??'',255);if(!self::canonical_ref_public_valid($owner,$ref,'knowledge-graph'))return RSV_Helpers::error('rsv_graph_ref_invalid',__('The knowledge-graph target is not currently public and valid.',RSV_TEXT_DOMAIN),422);return self::put_edge($fid,$reel['id'],sanitize_key($p['edge_type']??'related-to'),$owner,$ref,array('label'=>$p['label']??'','source_ref'=>$p['source_ref']??''));
			default: $defs=self::definitions();$slug=$defs[$fid]['slug']??'future';return self::put_object($fid,$slug,$reel['id'],$p['title']??'', $p, $p['public_id']??'');
		}
	}

}
