<?php
defined( 'ABSPATH' ) || exit;

trait RSV_Top20_Privacy_Integration_Trait {
	public static function privacy_exporters($exporters){$exporters['rsv-top20']=array('exporter_friendly_name'=>__('Reel Stories, responses and well-being preferences',RSV_TEXT_DOMAIN),'callback'=>array(__CLASS__,'privacy_export'));return $exporters;}

	public static function privacy_erasers($erasers){$erasers['rsv-top20']=array('eraser_friendly_name'=>__('Private Reel well-being preferences and unpublished temporal items',RSV_TEXT_DOMAIN),'callback'=>array(__CLASS__,'privacy_erase'));return $erasers;}

	public static function privacy_export($email,$page=1){$user=get_user_by('email',$email);if(!$user)return array('data'=>array(),'done'=>true);$data=array(array('group_id'=>'rsv-wellbeing','group_label'=>__('Reel well-being preferences',RSV_TEXT_DOMAIN),'item_id'=>'preferences-'.$user->ID,'data'=>array(array('name'=>__('Preferences',RSV_TEXT_DOMAIN),'value'=>wp_json_encode(self::preferences($user->ID))))));global $wpdb;$stories=(array)$wpdb->get_results($wpdb->prepare('SELECT public_id,title,status,expires_at FROM '.RSV_Helpers::table('stories').' WHERE owner_id=%d LIMIT 500',$user->ID),ARRAY_A);foreach($stories as $s)$data[]=array('group_id'=>'rsv-stories','group_label'=>__('Reel Stories',RSV_TEXT_DOMAIN),'item_id'=>$s['public_id'],'data'=>array(array('name'=>__('Title',RSV_TEXT_DOMAIN),'value'=>$s['title']),array('name'=>__('Status',RSV_TEXT_DOMAIN),'value'=>$s['status']),array('name'=>__('Expires',RSV_TEXT_DOMAIN),'value'=>$s['expires_at'])));return array('data'=>$data,'done'=>true);}

	public static function privacy_erase($email,$page=1){$user=get_user_by('email',$email);if(!$user)return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);global $wpdb;$removed=false;$removed=$wpdb->delete(RSV_Helpers::table('preferences'),array('user_id'=>$user->ID),array('%d'))||$removed;$wpdb->query($wpdb->prepare("UPDATE ".RSV_Helpers::table('stories')." SET status='removed',body='',destination_url='',version=version+1,updated_at=%s WHERE owner_id=%d AND status IN ('draft','review')",RSV_Helpers::now(),$user->ID));$wpdb->query($wpdb->prepare("UPDATE ".RSV_Helpers::table('responses')." SET status='removed',attribution_text='Removed unpublished response',version=version+1,updated_at=%s WHERE owner_id=%d AND status='review'",RSV_Helpers::now(),$user->ID));return array('items_removed'=>(bool)$removed,'items_retained'=>true,'messages'=>array(__('Published Stories, Highlights and responses are retained for governed correction/takedown rather than silently erased.',RSV_TEXT_DOMAIN)),'done'=>true);}

	public static function provider_manifest($manifest){$manifest=is_array($manifest)?$manifest:array();if(isset($manifest['provider_id'])){$manifest['entity_types']=array_values(array_unique(array_merge((array)($manifest['entity_types']??array()),array('reel','story','highlight','reel-response'))));$manifest['capabilities']=array_values(array_unique(array_merge((array)($manifest['capabilities']??array()),array('stories-status','highlights','attributed-responses','source-safety','wellbeing','youth-safe','value-insights'))));$manifest['provider_version']=2;return $manifest;}if(isset($manifest['file11-reels'])){$manifest['file11-reels']=self::provider_manifest($manifest['file11-reels']);}return $manifest;}

	public static function search_documents($documents,$query,$args=array()){$documents=is_array($documents)?$documents:array();$data=self::public_stories(min(20,max(1,absint($args['limit']??10))));if(is_wp_error($data))return $documents;$q=function_exists('mb_strtolower')?mb_strtolower((string)$query):strtolower((string)$query);foreach($data['items'] as $s){$hay=function_exists('mb_strtolower')?mb_strtolower($s['title'].' '.$s['body']):strtolower($s['title'].' '.$s['body']);if($q&&false===(function_exists('mb_strpos')?mb_strpos($hay,$q):strpos($hay,$q)))continue;$documents[]=array('provider_id'=>'file11-reels','provider_version'=>2,'native_id'=>$s['id'],'entity_type'=>'story','title'=>$s['title'],'excerpt'=>wp_trim_words($s['body'],24),'canonical_url'=>$s['url'],'published_at'=>$s['published_at'],'visibility'=>'public','safety'=>array('temporal','consent-current','source-reel-eligible'));}return $documents;}

	public static function author_items($items,$author_id,$args=array()){$items=is_array($items)?$items:array();foreach(self::public_highlights(absint($author_id),min(20,max(1,absint($args['limit']??10)))) as $h)$items[]=array('provider_id'=>'file11-reels','provider_version'=>2,'native_object_type'=>'highlight','native_id'=>$h['id'],'author_id'=>absint($author_id),'title'=>$h['title'],'canonical_url'=>$h['url'],'content_type'=>'highlight','visibility_state'=>'public','available_actions'=>array('open'=>$h['url']));return $items;}

	public static function story_cards($cards,$args=array()){$cards=is_array($cards)?$cards:array();$data=self::public_stories(min(12,max(1,absint($args['limit']??6))));if(is_wp_error($data))return $cards;foreach($data['items'] as $s)$cards[]=array('provider_id'=>'file11-reels','provider_version'=>2,'native_id'=>$s['id'],'title'=>$s['title'],'excerpt'=>wp_trim_words($s['body'],18),'canonical_url'=>$s['url'],'expires_at'=>$s['expires_at'],'story_type'=>$s['type']);return $cards;}

	public static function highlight_collections($collections,$owner_id,$args=array()){$collections=is_array($collections)?$collections:array();return array_merge($collections,self::public_highlights(absint($owner_id),min(30,max(1,absint($args['limit']??20)))));}

	public static function composer_contracts($contracts){$contracts=is_array($contracts)?$contracts:array();$contracts['file11-reel']=array('owner'=>'File 11','media_owner'=>'File 10','contract_version'=>RSV_CONTRACT_VERSION,'fields'=>array('video_id','title','topic','language','caption','cover_id','disclosure','visibility','source_title','source_url','transcript_url','safety_summary','allow_response','patient_reuse_policy'),'duration'=>array('min'=>60,'max'=>600,'authority'=>'File 10'),'write'=>'versioned File 11 command only');$contracts['file11-story-status']=array('owner'=>'File 11','source'=>'existing eligible Reel','max_hours'=>24,'types'=>RSV_Contracts::STORY_TYPES,'media_owner'=>'File 10');$contracts['file11-response']=array('owner'=>'File 11 relationship','source_and_response'=>'existing eligible Reels','attribution'=>'required','patient_reuse'=>'verified consent when applicable');return $contracts;}
}
