<?php
defined( 'ABSPATH' ) || exit;

trait RSV_Top20_Experience_Trait {
	public static function rest_pre_dispatch( $result, $server, $request ) {
		if ( null !== $result ) return $result;
		$route=$request->get_route(); $method=$request->get_method();
		if ( '/rsv/v1/reels' === $route && 'POST' === $method ) {
			$p=(array)$request->get_json_params();
			if ( ''===trim(RSV_Helpers::text($p['source_title']??'',255)) || ''===trim(RSV_Helpers::textarea($p['safety_summary']??'',2000)) ) return RSV_Helpers::error('rsv_source_safety_required',__('A reviewed source label and safety summary are required.',RSV_TEXT_DOMAIN),422);
		}
		if ( '/rsv/v1/history' === $route && 'GET' === $method && is_user_logged_in() ) return rest_ensure_response(self::history_cursor(get_current_user_id(),$request->get_param('limit')?:50,$request->get_param('cursor')?:''));
		if ( preg_match('#^/rsv/v1/reels/reel_[a-f0-9-]{36}/(view-session|progress)$#',$route) && !empty(self::preferences()['history_paused']) ) return rest_ensure_response(array('paused'=>true,'session_id'=>'','saved'=>false));
		if ( preg_match('#^/rsv/v1/reels/(reel_[a-f0-9-]{36})/publish$#',$route,$m) ) { $gate=self::publication_gate(RSV_Repository::find($m[1],true)); if(is_wp_error($gate))return $gate; }
		return $result;
	}

	public static function rest_post_dispatch( $response, $server, $request ) {
		if ( '/rsv/v1/reels' !== $request->get_route() || 'POST' !== $request->get_method() || is_wp_error($response) || !($response instanceof WP_REST_Response) || $response->get_status()>=400 ) return $response;
		$data=$response->get_data();
		if ( !is_array($data) || empty($data['id']) ) return $response;
		$reel=RSV_Repository::find($data['id'],true); if(!$reel)return self::rest_error_response(RSV_Helpers::error('rsv_create_reel_missing',__('The created Reel could not be verified.',RSV_TEXT_DOMAIN),500));
		$context=self::save_context($reel,(array)$request->get_json_params());
		if(is_wp_error($context)){
			self::compensate_failed_reel_create($reel,$request->get_header('Idempotency-Key'),$context);
			return self::rest_error_response($context);
		}
		$data['source_safety']=$context;$response->set_data($data);return $response;
	}

	private static function compensate_failed_reel_create( $reel, $idem_key, $error ) {
		if(!is_array($reel)||'draft'!==($reel['status']??'')||absint($reel['owner_id']??0)!==get_current_user_id())return false;
		global $wpdb;$rid=absint($reel['id']);
		return RSV_DB::transaction(static function()use($wpdb,$rid,$idem_key,$error){
			$wpdb->delete(RSV_Helpers::table('reel_context'),array('reel_id'=>$rid),array('%d'));
			$wpdb->delete(RSV_Helpers::table('outbox'),array('object_type'=>'reel','object_id'=>$rid),array('%s','%d'));
			$wpdb->delete(RSV_Helpers::table('audit'),array('object_type'=>'reel','object_id'=>$rid),array('%s','%d'));
			$deleted=$wpdb->delete(RSV_Helpers::table('reels'),array('id'=>$rid,'owner_id'=>get_current_user_id(),'status'=>'draft'),array('%d','%d','%s'));
			if($idem_key)$wpdb->delete(RSV_Helpers::table('idempotency'),array('actor_id'=>get_current_user_id(),'scope_key'=>'create_reel','idem_key'=>RSV_Helpers::text($idem_key,120)),array('%d','%s','%s'));
			RSV_Helpers::audit('reel_create_compensation',$rid,'rollback','draft','removed',is_wp_error($error)?$error->get_error_code():'context_failure');
			return 1===$deleted;
		});
	}

	private static function rest_error_response($error){$data=is_wp_error($error)?(array)$error->get_error_data():array();$status=isset($data['status'])?absint($data['status']):500;return new WP_REST_Response(array('code'=>is_wp_error($error)?$error->get_error_code():'rsv_unknown_error','message'=>is_wp_error($error)?$error->get_error_message():__('The request could not be completed.',RSV_TEXT_DOMAIN),'data'=>$data),$status);}
	public static function rest_stories($r){$d=self::public_stories($r->get_param('limit')?:20,$r->get_param('cursor')?:'');return is_wp_error($d)?$d:rest_ensure_response($d);} public static function rest_story($r){$d=self::story_dto(self::story_row($r['id'],true));return $d?rest_ensure_response($d):RSV_Helpers::error('rsv_story_not_found',__('Story not found.',RSV_TEXT_DOMAIN),404);} public static function rest_story_create($r){$x=self::create_story((array)$r->get_json_params(),$r->get_header('Idempotency-Key'));return is_wp_error($x)?$x:rest_ensure_response($x);} public static function rest_story_publish($r){$x=self::publish_story($r['id'],absint($r->get_param('version')));return is_wp_error($x)?$x:rest_ensure_response($x);} public static function rest_highlight_add($r){$x=self::add_highlight($r['id'],$r->get_param('title'),$r->get_param('highlight_id'));return is_wp_error($x)?$x:rest_ensure_response($x);} public static function rest_highlights($r){return rest_ensure_response(array('items'=>self::public_highlights(absint($r['owner_id']),$r->get_param('limit')?:20)));} public static function rest_responses($r){return rest_ensure_response(array('items'=>self::public_responses($r['id'],$r->get_param('limit')?:20)));} public static function rest_response_create($r){$x=self::create_response($r['id'],(array)$r->get_json_params());return is_wp_error($x)?$x:rest_ensure_response($x);} public static function rest_response_publish($r){$x=self::publish_response($r['id'],absint($r->get_param('version')));return is_wp_error($x)?$x:rest_ensure_response($x);} public static function rest_preferences(){RSV_Helpers::no_cache_private();return rest_ensure_response(self::preferences());} public static function rest_preferences_update($r){$x=self::save_preferences((array)$r->get_json_params());return is_wp_error($x)?$x:rest_ensure_response($x);} public static function rest_signal($r){$x=self::record_signal(RSV_Repository::find($r['id'],true),$r->get_param('signal'));return is_wp_error($x)?$x:rest_ensure_response($x);} public static function rest_value_insights(){RSV_Helpers::no_cache_private();return rest_ensure_response(array('items'=>self::value_insights(get_current_user_id())));}

	public static function register_assets(){wp_register_style('rsv-top20',RSV_URL.'assets/css/rsv-top20.css',array('rsv'),RSV_VERSION);wp_register_script('rsv-top20',RSV_URL.'assets/js/rsv-top20.js',array('rsv'),RSV_VERSION,true);if(self::is_context())self::enqueue_assets();}
	private static function is_context(){if(is_admin())return false;if(get_query_var('rsv_reel')||get_query_var('rsv_history')||get_query_var('rsv_insights')||get_query_var('rsv_stories')||get_query_var('rsv_story')||get_query_var('rsv_highlights')||get_query_var('rsv_preferences')||get_query_var('rsv_value_insights')||get_query_var('rsv_respond'))return true;$u=isset($_SERVER['REQUEST_URI'])?sanitize_text_field(wp_unslash($_SERVER['REQUEST_URI'])):'';return false!==strpos($u,'/reels');}
	private static function enqueue_assets(){wp_enqueue_style('rsv');wp_enqueue_script('rsv');wp_enqueue_style('rsv-top20');wp_enqueue_script('rsv-top20');wp_localize_script('rsv-top20','RSV_TOP20',array('root'=>esc_url_raw(rest_url(RSV_Contracts::API_NAMESPACE)),'nonce'=>wp_create_nonce('wp_rest'),'loggedIn'=>is_user_logged_in(),'storiesUrl'=>home_url('/reels/stories/'),'preferencesUrl'=>home_url('/account/reels/preferences/'),'insightsUrl'=>home_url('/account/reels/value-insights/'),'respondUrl'=>home_url('/reels/respond/'),'preferences'=>self::preferences(),'canSubmit'=>self::can_submit(),'i18n'=>array('naturalStop'=>__('Natural pause: take a moment before continuing.',RSV_TEXT_DOMAIN),'sessionLimit'=>__('Your chosen Reel session limit has been reached.',RSV_TEXT_DOMAIN),'lateNight'=>__('Late-night reminder: consider resting and returning later.',RSV_TEXT_DOMAIN),'continue'=>__('Continue by choice',RSV_TEXT_DOMAIN),'error'=>__('Additional Reel context is temporarily unavailable.',RSV_TEXT_DOMAIN))));}

	public static function enhance_shortcode($output,$tag,$attr,$m){if('rsv_create'===$tag){$f='<fieldset class="rsv-top20-context-fields"><legend>'.esc_html__('Source, accessibility and response context',RSV_TEXT_DOMAIN).'</legend><label>'.esc_html__('Source label',RSV_TEXT_DOMAIN).'<input name="source_title" maxlength="255" required></label><label>'.esc_html__('Source URL (optional)',RSV_TEXT_DOMAIN).'<input name="source_url" type="url" maxlength="500"></label><label>'.esc_html__('Transcript URL',RSV_TEXT_DOMAIN).'<input name="transcript_url" type="url" maxlength="500"></label><label>'.esc_html__('Safety summary',RSV_TEXT_DOMAIN).'<textarea name="safety_summary" maxlength="2000" required></textarea></label><label><input name="allow_response" type="checkbox" value="1" checked> '.esc_html__('Allow attributed educational responses/remixes',RSV_TEXT_DOMAIN).'</label><label>'.esc_html__('Patient-media reuse policy',RSV_TEXT_DOMAIN).'<select name="patient_reuse_policy"><option value="explicit-consent-required">'.esc_html__('Explicit verified consent required',RSV_TEXT_DOMAIN).'</option><option value="not-applicable">'.esc_html__('Not a patient case',RSV_TEXT_DOMAIN).'</option><option value="disabled">'.esc_html__('Responses disabled',RSV_TEXT_DOMAIN).'</option></select></label></fieldset>';$output=preg_replace('/<\/form>/',$f.'</form>',$output,1);}if('rsv_reels'===$tag)$output.=self::render_context_index();if('rsv_insights'===$tag&&self::can_insights())$output.=self::render_value_insights();return $output;}
	private static function render_context_index(){$d=RSV_Repository::feed(array('limit'=>12,'sort'=>'recommended'));if(is_wp_error($d)||empty($d['items']))return '';$h='<section class="rsv-context-index"><h2>'.esc_html__('Sources and safety for this page',RSV_TEXT_DOMAIN).'</h2><ul>';foreach($d['items'] as $x){$c=$x['source_safety']??array();$h.='<li><strong>'.esc_html($x['title']).'</strong>: '.esc_html($c['source_title']??__('Source pending review',RSV_TEXT_DOMAIN)).'</li>'; }return $h.'</ul></section>';}
	public static function single_context_before_footer(){if(!get_query_var('rsv_reel'))return;$r=RSV_Repository::find(get_query_var('rsv_reel'),true);if(RSV_Security::can_view_reel($r))echo wp_kses_post(self::render_context_card($r));}
	private static function render_context_card($r){$c=self::public_context($r);$h='<section class="rsv-context-card"><h2>'.esc_html__('Source, transcript and safety',RSV_TEXT_DOMAIN).'</h2><p><strong>'.esc_html__('Source',RSV_TEXT_DOMAIN).':</strong> '.esc_html($c['source_title']?:__('Pending reviewed source label',RSV_TEXT_DOMAIN));if($c['source_url'])$h.=' — <a data-rsv-source-open data-reel="'.esc_attr($r['public_id']).'" href="'.esc_url($c['source_url']).'">'.esc_html__('Open source',RSV_TEXT_DOMAIN).'</a>';$h.='</p><p><strong>'.esc_html__('Safety',RSV_TEXT_DOMAIN).':</strong> '.esc_html($c['safety_summary']).'</p>';if($c['transcript_url'])$h.='<p><a href="'.esc_url($c['transcript_url']).'">'.esc_html__('Open transcript',RSV_TEXT_DOMAIN).'</a></p>';if($c['response_allowed']&&self::can_submit())$h.='<p><a href="'.esc_url(add_query_arg('source',$r['public_id'],home_url('/reels/respond/'))).'">'.esc_html__('Create an attributed response/remix',RSV_TEXT_DOMAIN).'</a></p>';return $h.'</section>';}

	public static function route_request(){if(get_query_var('rsv_stories'))self::render_page(__('Stories / Status',RSV_TEXT_DOMAIN),self::render_stories());if(get_query_var('rsv_story')){$d=self::story_dto(self::story_row(get_query_var('rsv_story'),true));if(!$d)status_header(404);self::render_page(__('Story',RSV_TEXT_DOMAIN),$d?self::render_story_dto($d):'<p>'.esc_html__('Story unavailable.',RSV_TEXT_DOMAIN).'</p>');}if(get_query_var('rsv_highlights'))self::render_page(__('Highlights',RSV_TEXT_DOMAIN),self::render_highlights(absint(get_query_var('rsv_highlights'))));if(get_query_var('rsv_preferences'))self::render_page(__('Reel well-being and privacy',RSV_TEXT_DOMAIN),self::render_preferences(),true);if(get_query_var('rsv_value_insights'))self::render_page(__('Value insights',RSV_TEXT_DOMAIN),self::render_value_insights(),true);if(get_query_var('rsv_respond'))self::render_page(__('Attributed Reel response',RSV_TEXT_DOMAIN),self::render_response_form(),true);}
	private static function render_page($title,$body,$private=false){if($private)RSV_Helpers::no_cache_private();self::enqueue_assets();add_filter('pre_get_document_title',static function()use($title){return $title;});get_header();echo '<main class="rsv-shell rsv-top20-page"><nav class="rsv-local-nav"><a href="'.esc_url(home_url('/reels/')).'">'.esc_html__('Reels',RSV_TEXT_DOMAIN).'</a> <a href="'.esc_url(home_url('/reels/stories/')).'">'.esc_html__('Stories / Status',RSV_TEXT_DOMAIN).'</a> <a href="'.esc_url(home_url('/account/reels/preferences/')).'">'.esc_html__('Well-being',RSV_TEXT_DOMAIN).'</a></nav><h1>'.esc_html($title).'</h1>'.$body.'</main>';get_footer();exit;}
	private static function render_stories(){$d=self::public_stories(30,'');if(is_wp_error($d)||empty($d['items']))return '<p>'.esc_html__('No active Stories are available.',RSV_TEXT_DOMAIN).'</p>';$h='';foreach($d['items'] as $x)$h.=self::render_story_dto($x);return $h;}
	private static function render_story_dto($d){return '<article class="rsv-story"><h2><a href="'.esc_url($d['url']).'">'.esc_html($d['title']).'</a></h2><p>'.esc_html($d['body']).'</p><p><a href="'.esc_url($d['reel']['url']).'">'.esc_html__('Open source Reel',RSV_TEXT_DOMAIN).'</a></p></article>';}
	private static function render_highlights($uid){$xs=self::public_highlights($uid,30);if(!$xs)return '<p>'.esc_html__('No consent-current Highlights are available.',RSV_TEXT_DOMAIN).'</p>';$h='';foreach($xs as $x){$h.='<section><h2>'.esc_html($x['title']).'</h2>';foreach($x['items'] as $s)$h.=self::render_story_dto($s);$h.='</section>';}return $h;}
	private static function render_preferences(){if(!is_user_logged_in())return '<p>'.esc_html__('Sign in to control private history and well-being settings.',RSV_TEXT_DOMAIN).'</p>';$p=self::preferences();$disabled=$p['mandatory_youth_safe']?' disabled':'';$h='<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="rsv_top20_preferences"><input type="hidden" name="version" value="'.absint($p['version']).'">'.wp_nonce_field('rsv_top20_preferences','_rsv_nonce',true,false).'<label><input type="checkbox" name="youth_safe" value="1"'.checked($p['youth_safe'],true,false).$disabled.'> '.esc_html__('Youth-safe recommendations',RSV_TEXT_DOMAIN).'</label><label><input type="checkbox" name="history_paused" value="1"'.checked($p['history_paused'],true,false).'> '.esc_html__('Pause private watch history',RSV_TEXT_DOMAIN).'</label><label>'.esc_html__('Session reminder minutes',RSV_TEXT_DOMAIN).'<input type="number" name="session_limit_minutes" min="5" max="60" value="'.absint($p['session_limit_minutes']).'"></label><label>'.esc_html__('Natural stop after Reel changes',RSV_TEXT_DOMAIN).'<input type="number" name="natural_stop_every" min="5" max="25" value="'.absint($p['natural_stop_every']).'"></label><label><input type="checkbox" name="late_night_reminder" value="1"'.checked($p['late_night_reminder'],true,false).'> '.esc_html__('Late-night reminder',RSV_TEXT_DOMAIN).'</label><button>'.esc_html__('Save preferences',RSV_TEXT_DOMAIN).'</button></form>';if($p['mandatory_youth_safe'])$h.='<p>'.esc_html__('Youth-safe mode is required by the active age claim.',RSV_TEXT_DOMAIN).'</p>';return $h;}
	private static function render_response_form(){if(!self::can_submit())return '<p>'.esc_html__('Verified publishing access is required.',RSV_TEXT_DOMAIN).'</p>';$source=isset($_GET['source'])?sanitize_text_field(wp_unslash($_GET['source'])):'';return '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="rsv_top20_response">'.wp_nonce_field('rsv_top20_response','_rsv_nonce',true,false).'<label>'.esc_html__('Source Reel public ID',RSV_TEXT_DOMAIN).'<input name="source_reel_id" value="'.esc_attr($source).'" required></label><label>'.esc_html__('Your response Reel public ID',RSV_TEXT_DOMAIN).'<input name="response_reel_id" required></label><label>'.esc_html__('Attribution text',RSV_TEXT_DOMAIN).'<input name="attribution_text" maxlength="500"></label><label><input type="checkbox" name="patient_reuse_consent" value="1"> '.esc_html__('Verified patient-media reuse consent exists where required',RSV_TEXT_DOMAIN).'</label><button>'.esc_html__('Submit attributed response for review',RSV_TEXT_DOMAIN).'</button></form>';}
	private static function render_value_insights(){if(!self::can_insights())return '<p>'.esc_html__('Creator insight access is restricted.',RSV_TEXT_DOMAIN).'</p>';$rows=self::value_insights(get_current_user_id());if(!$rows)return '<p>'.esc_html__('No Reel insight rows are available.',RSV_TEXT_DOMAIN).'</p>';$h='<table><thead><tr><th>'.esc_html__('Reel',RSV_TEXT_DOMAIN).'</th><th>'.esc_html__('Completion',RSV_TEXT_DOMAIN).'</th><th>'.esc_html__('Source opens',RSV_TEXT_DOMAIN).'</th><th>'.esc_html__('Shares',RSV_TEXT_DOMAIN).'</th><th>'.esc_html__('Saves',RSV_TEXT_DOMAIN).'</th><th>'.esc_html__('Meaningful comments',RSV_TEXT_DOMAIN).'</th><th>'.esc_html__('Harm reports',RSV_TEXT_DOMAIN).'</th></tr></thead><tbody>';foreach($rows as $r){$h.='<tr><td>'.esc_html($r['title']).'</td>';if($r['insufficient_data'])$h.='<td colspan="6">'.esc_html__('Insufficient aggregate data',RSV_TEXT_DOMAIN).'</td>';else$h.='<td>'.absint($r['completions']).'/'.absint($r['views']).'</td><td>'.absint($r['source_opens']).'</td><td>'.absint($r['shares']).'</td><td>'.(null===$r['saves']?esc_html__('Unavailable',RSV_TEXT_DOMAIN):absint($r['saves'])).'</td><td>'.(null===$r['meaningful_comments']?esc_html__('Unavailable',RSV_TEXT_DOMAIN):absint($r['meaningful_comments'])).'</td><td>'.absint($r['harm_reports']).'</td>';$h.='</tr>';}return $h.'</tbody></table>';}
	private static function redirect_with_status($url,$result){wp_safe_redirect(add_query_arg(is_wp_error($result)?array('rsv_status'=>'error','rsv_message'=>$result->get_error_code()):array('rsv_status'=>'success'),$url));exit;}
	public static function admin_story(){if(!is_user_logged_in())auth_redirect();check_admin_referer('rsv_top20_story','_rsv_nonce');self::redirect_with_status(home_url('/reels/stories/'),self::create_story(wp_unslash($_POST),wp_generate_uuid4()));} public static function admin_response(){if(!is_user_logged_in())auth_redirect();check_admin_referer('rsv_top20_response','_rsv_nonce');$d=wp_unslash($_POST);self::redirect_with_status(home_url('/reels/respond/'),self::create_response(sanitize_text_field($d['source_reel_id']??''),$d));} public static function admin_highlight(){if(!is_user_logged_in())auth_redirect();check_admin_referer('rsv_top20_highlight','_rsv_nonce');self::redirect_with_status(home_url('/reels/stories/'),self::add_highlight(sanitize_text_field(wp_unslash($_POST['story_id']??'')),sanitize_text_field(wp_unslash($_POST['title']??'')),sanitize_text_field(wp_unslash($_POST['highlight_id']??''))));} public static function admin_preferences(){if(!is_user_logged_in())auth_redirect();check_admin_referer('rsv_top20_preferences','_rsv_nonce');self::redirect_with_status(home_url('/account/reels/preferences/'),self::save_preferences(wp_unslash($_POST)));}
	public static function robots($r){if(get_query_var('rsv_preferences')||get_query_var('rsv_value_insights')||get_query_var('rsv_respond')){$r['noindex']=true;$r['nofollow']=true;$r['noarchive']=true;}return $r;}
	public static function maintenance(){self::expire_stories();global $wpdb;$wpdb->query($wpdb->prepare('DELETE FROM '.RSV_Helpers::table('value_signals').' WHERE day_key<%s',gmdate('Y-m-d',time()-180*DAY_IN_SECONDS)));}
}
