<?php
error_reporting(E_ALL);
define('ABSPATH',__DIR__.'/');define('RSV_TEXT_DOMAIN','test');define('RSV_CONTRACT_VERSION',2);define('DAY_IN_SECONDS',86400);define('HOUR_IN_SECONDS',3600);
class WP_Error {private $code;private $message;private $data;public function __construct($c,$m,$d=array()){$this->code=$c;$this->message=$m;$this->data=$d;}public function get_error_code(){return $this->code;}public function get_error_message(){return $this->message;}public function get_error_data(){return $this->data;}}
function is_wp_error($v){return $v instanceof WP_Error;}function __($s){return $s;}function sanitize_key($s){return strtolower(preg_replace('/[^a-z0-9_\-]/i','',(string)$s));}function sanitize_text_field($s){return trim(strip_tags((string)$s));}function sanitize_textarea_field($s){return trim(strip_tags((string)$s));}function wp_json_encode($v,$flags=0){return json_encode($v,$flags);}function wp_generate_uuid4(){return '123e4567-e89b-12d3-a456-426614174000';}function wp_salt($scheme='auth'){return 'unit-test-'.$scheme;}function current_time(){return '2026-08-06 12:00:00';}function get_current_user_id(){return $GLOBALS['rsv_user']??0;}function is_user_logged_in(){return !empty($GLOBALS['rsv_logged']);}function current_user_can(){return !empty($GLOBALS['rsv_admin']);}function user_can($id,$cap){return !empty($GLOBALS['rsv_admin']);}function apply_filters($tag,$value){$args=func_get_args();if(isset($GLOBALS['rsv_filters'][$tag]))return $GLOBALS['rsv_filters'][$tag](...array_slice($args,1));return $value;}function has_filter($tag){return isset($GLOBALS['rsv_filters'][$tag]);}function wp_parse_args($a,$b){return array_merge($b,$a);}function wp_unslash($v){return $v;}function esc_url_raw($v){return filter_var($v,FILTER_VALIDATE_URL)?$v:'';}function wp_parse_url($u,$c=-1){return parse_url($u,$c);}function absint($v){return abs((int)$v);}function get_transient(){return false;}function set_transient(){return true;}function get_userdata(){return false;}function get_author_posts_url(){return '/author';}function home_url($p=''){return 'https://example.test'.$p;}function wp_get_attachment_image_url(){return '';}function wp_attachment_is_image(){return true;}function get_option($k,$d=false){return $d;}function add_option(){return true;}function update_option(){return true;}function delete_option(){return true;}
require_once __DIR__.'/../11-reels-foundation/includes/class-rsv-contracts.php';
require_once __DIR__.'/../11-reels-foundation/includes/class-rsv-helpers.php';
require_once __DIR__.'/../11-reels-foundation/includes/class-rsv-state-machine.php';
require_once __DIR__.'/../11-reels-foundation/includes/class-rsv-ranking.php';
