<?php
$root = dirname( __DIR__ ) . '/11-reels-foundation';
$read = static function ( $path ) { $v = file_get_contents( $path ); if ( false === $v ) throw new RuntimeException( "Cannot read $path" ); return $v; };
$f = array(
 'bootstrap'=>$read($root.'/11-reels-foundation.php'),
 'security'=>$read($root.'/includes/class-rsv-security.php'),
 'file10'=>$read($root.'/includes/class-rsv-file10.php'),
 'reels'=>$read($root.'/includes/class-rsv-reels.php'),
 'db'=>$read($root.'/includes/class-rsv-db.php'),
 'repo'=>$read($root.'/includes/class-rsv-repository.php'),
 'helpers'=>$read($root.'/includes/class-rsv-helpers.php'),
 'frontend'=>$read($root.'/includes/class-rsv-frontend.php'),
 'privacy'=>$read($root.'/includes/class-rsv-privacy.php'),
 'jobs'=>$read($root.'/includes/class-rsv-jobs.php'),
 'migration'=>$read($root.'/includes/class-rsv-migration.php'),
 'plugin'=>$read($root.'/includes/class-rsv-plugin.php'),
 'diagnostics'=>$read($root.'/includes/class-rsv-diagnostics.php'),
 'integrations'=>$read($root.'/includes/class-rsv-integrations.php'),
 'top20'=>$read($root.'/includes/class-rsv-top20.php'),
 'context'=>$read($root.'/includes/trait-rsv-top20-context.php'),
 'responses'=>$read($root.'/includes/trait-rsv-top20-responses.php'),
 'stories'=>$read($root.'/includes/trait-rsv-top20-stories.php'),
 'privacy20'=>$read($root.'/includes/trait-rsv-top20-privacy-integration.php'),
 'js20'=>$read($root.'/assets/js/rsv-top20.js'),
 'uninstall'=>$read($root.'/uninstall.php'),
);
$must = array(
 ['bootstrap', 'Version: 1.1.0-rc6'],
 ['bootstrap', "define( 'RSV_VERSION', '1.1.0-rc6' )"],
 ['bootstrap', "define( 'RSV_CONTRACT_VERSION', 5 )"],
 ['security', "'guardian_ok'          => ! \$guardian_required || \$guardian_verified"],
 ['file10', "is_callable( array( 'VWLB_Repository', 'find' ) )"],
 ['file10', "is_callable( array( 'VWLB_Videos', 'playback' ) )"],
 ['file10', "defined( 'VWLB_Contracts::EVENT_VERSION' )"],
 ['reels', "if ( 'review' !== ( \$reel['status'] ?? '' ) )"],
 ['reels', "RSV_Top20::publication_gate( \$reel )"],
 ['security', "\$active = 'active' === ( \$claims['status'] ?? '' )"],
 ['security', "strtotime( \$row['expires_at'] . ' UTC' ) < time()"],
 ['db', "false === \$wpdb->query( 'START TRANSACTION' )"],
 ['db', "false === \$wpdb->query( 'COMMIT' )"],
 ['db', "false === \$wpdb->query( 'ROLLBACK' )"],
 ['reels', '$age_days'],
 ['reels', '$creator_count'],
 ['repo', '$extra_eligible'],
 ['repo', 'private static function safe_destination_url'],
 ['top20', "const SCHEMA_VERSION = '1.1.0'"],
 ['top20', 'value_signal_receipts'],
 ['top20', 'const INSIGHT_MINIMUM = 5'],
 ['responses', "if ( ! is_user_logged_in() ) return RSV_Helpers::error( 'rsv_signal_login_required'"],
 ['responses', 'INSERT IGNORE INTO $receipts'],
 ['stories', "RSV_Helpers::outbox( 'StoryExpired'"],
 ['js20', 'let activeSeconds = 0'],
 ['js20', "document.querySelector('[data-rsv-reel]')"],
 ['frontend', 'JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT'],
 ['helpers', 'public static function label( $value )'],
 ['privacy', 'rp.reporter_id=%d OR rp.appellant_id=%d'],
 ['privacy', "array( 'impressions', 'value_signal_receipts' )"],
 ['privacy', 'RSV_DB::transaction'],
 ['jobs', "RSV_Helpers::outbox( 'ReelMediaReadyForReview'"],
 ['jobs', 'rsv_dependency_evidence_failed'],
 ['migration', 'rsv_reconcile_evidence_failed'],
 ['migration', 'rsv_rollback_evidence_failed'],
 ['plugin', 'rsv_feed_page_failed'],
 ['plugin', 'rsv_create_page_failed'],
 ['diagnostics', 'rsv_repair_evidence_failed'],
 ['integrations', 'const PROVIDER_VERSION = 3'],
 ['privacy20', "'provider_version'] = 3"],
 ['uninstall', 'value_signal_receipts'],
);
foreach ($must as [$key,$needle]) {
  if (false === strpos($f[$key], $needle)) { fwrite(STDERR, "Missing RC6 marker [$key]: $needle\n"); exit(1); }
}
$forbidden = array(
 ['bootstrap', "Version: 1.1.0-rc5"],
 ['bootstrap', "define( 'RSV_CONTRACT_VERSION', 4 )"],
 ['security', "'guardian_ok'          => ! \$guardian_required || ! \$guardian_verified"],
 ['reels', "in_array( \$reel['status'] ?? '', array( 'review', 'restricted'"],
 ['top20', "const INSIGHT_MINIMUM = 3"],
 ['integrations', 'const PROVIDER_VERSION = 2'],
 ['privacy', 'rr.owner_id'],
);
foreach ($forbidden as [$key,$needle]) {
  if (false !== strpos($f[$key], $needle)) { fwrite(STDERR, "Forbidden pre-RC6 pattern [$key]: $needle\n"); exit(1); }
}
echo "RC6 forty-review corrective contracts PASS\n";
